version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
    - 5432:5432/tcp
  advinheme:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: AdvinheMe
    volumes:
    - .:/app
    ports:
        - 8000:8000

volumes:
  postgres_data: