# Generated by Django 3.0.7 on 2022-08-06 03:07

from django.db import migrations, models
import django.db.models.deletion
import palavras.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PalavraDia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_palavra_dia', models.IntegerField(verbose_name='Dia da Palavra')),
                ('palavra', models.CharField(blank=True, max_length=40, verbose_name='Palavra do dia')),
            ],
            options={
                'verbose_name': 'Palavra do dia',
            },
        ),
        migrations.CreateModel(
            name='Palavra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicao', models.IntegerField(default=palavras.models.verificarPalavra, editable=False, null=True, verbose_name='Posição')),
                ('palavra', models.CharField(blank=True, max_length=40, verbose_name='Palavra')),
                ('palavra_do_dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palavra_dia', to='palavras.PalavraDia', verbose_name='Dia da Palavra')),
            ],
            options={
                'verbose_name': 'Palavra',
            },
        ),
    ]
