# Generated by Django 3.0.7 on 2022-08-06 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('palavras', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='palavra',
            options={},
        ),
        migrations.AlterModelOptions(
            name='palavradia',
            options={},
        ),
    ]
