# Generated by Django 3.0.7 on 2022-08-08 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('palavras', '0002_auto_20220806_0311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='palavra',
            name='palavra_do_dia',
        ),
        migrations.AddField(
            model_name='palavra',
            name='dia_da_palavra',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dia_da_palavra', to='palavras.PalavraDia', verbose_name='Dia da Palavra'),
        ),
    ]
