# Generated by Django 3.0.7 on 2022-08-09 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palavras', '0003_auto_20220808_0328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='palavradia',
            name='id',
        ),
        migrations.AlterField(
            model_name='palavradia',
            name='id_palavra_dia',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Dia da Palavra'),
        ),
    ]
